name: CI/CD Frontend

on:
  push:
    branches:
      - main
      - dev
      - qa
      - prod

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm test

      - name: Build Frontend
        run: npm run build

      - name: Deploy Frontend
        run: |
          if [ "${{ github.ref_name }}" == "dev" ]; then
            echo "Deploying to Development Environment"
            # Exemplo: Vercel CLI
            npm install -g vercel
            vercel deploy --prod --token=$VERCEL_TOKEN
          elif [ "${{ github.ref_name }}" == "qa" ]; then
            echo "Deploying to QA Environment"
            # Comando para deploy no ambiente QA
          elif [ "${{ github.ref_name }}" == "prod" ]; then
            echo "Deploying to Production"
            # Comando para deploy em produção
          fi
